version: "3"
services:
  mysql:
    image: "mysql:8.0.31"
    networks:
      - jamfnet
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "jamfsw03"
      MYSQL_DATABASE: "jamfsoftware"
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
  jamfpro:
    image: "jamfpro:10.42.1"
    networks:
      - jamfnet
    ports:
      - "8443:8080"
    environment:
      DATABASE_USERNAME: "root"
      DATABASE_PASSWORD: "jamfsw03"
      DATABASE_HOST: "mysql"
    depends_on:
      - mysql
networks:
  jamfnet:
